insert into public.competencies (name, slug, category, description)
values
  ('Agentic commerce', 'agentic-commerce', 'knowledge', 'Commerce workflows and operating models involving AI agents.'),
  ('Composable commerce', 'composable-commerce', 'knowledge', 'Composable commerce architectures and capability selection.'),
  ('Retail operations', 'retail-operations', 'knowledge', 'Retail operating processes across channels and functions.'),
  ('Product information management', 'product-information-management', 'knowledge', 'Product information systems, ownership and publishing.'),
  ('Product-data quality', 'product-data-quality', 'knowledge', 'Product data completeness, consistency and governance.'),
  ('Commerce platforms', 'commerce-platforms', 'knowledge', 'Commerce platform capabilities and operating models.'),
  ('Retail media', 'retail-media', 'knowledge', 'Retail media strategy, operations and measurement.'),
  ('Partner ecosystems', 'partner-ecosystems', 'knowledge', 'Technology, agency and systems-integrator ecosystems.'),
  ('Enterprise procurement', 'enterprise-procurement', 'knowledge', 'Enterprise procurement and technology buying processes.'),
  ('Customer experience', 'customer-experience', 'knowledge', 'Customer experience across commerce and service journeys.'),
  ('Platform assessment', 'platform-assessment', 'practical_capability', 'Assess platform fit, constraints and decision criteria.'),
  ('Replatforming strategy', 'replatforming-strategy', 'practical_capability', 'Plan and govern commerce platform replacement.'),
  ('Vendor evaluation', 'vendor-evaluation', 'practical_capability', 'Compare vendors against evidence, requirements and trade-offs.'),
  ('Commerce architecture', 'commerce-architecture', 'practical_capability', 'Design commerce architecture across platforms and systems.'),
  ('Product-data enrichment', 'product-data-enrichment', 'practical_capability', 'Improve product records for discovery, comparison and channels.'),
  ('Go-to-market design', 'go-to-market-design', 'practical_capability', 'Design a focused, measurable go-to-market motion.'),
  ('Partner development', 'partner-development', 'practical_capability', 'Build and activate productive commercial partnerships.'),
  ('Commercial negotiation', 'commercial-negotiation', 'practical_capability', 'Structure and negotiate technology and partnership agreements.'),
  ('Program leadership', 'program-leadership', 'practical_capability', 'Coordinate a multi-party program toward clear outcomes.'),
  ('Marketplace operations', 'marketplace-operations', 'practical_capability', 'Manage marketplace sellers, catalogue, orders and operations.'),
  ('Workflow automation', 'workflow-automation', 'practical_capability', 'Automate bounded business workflows with appropriate controls.'),
  ('Systems integration', 'systems-integration', 'practical_capability', 'Connect business systems and manage operational interfaces.'),
  ('Product discovery optimization', 'product-discovery-optimization', 'practical_capability', 'Improve product visibility and findability across discovery surfaces.'),
  ('AI agent governance', 'ai-agent-governance', 'practical_capability', 'Define permissions, oversight and accountability for AI agents.'),
  ('Evidence-led decision-making', 'evidence-led-decision-making', 'way_of_working', 'Use relevant evidence and explicit assumptions to make decisions.'),
  ('Cross-functional collaboration', 'cross-functional-collaboration', 'way_of_working', 'Work effectively across business and technical functions.'),
  ('Constructive challenge', 'constructive-challenge', 'way_of_working', 'Surface risks and alternatives respectfully and productively.'),
  ('Complex-problem simplification', 'complex-problem-simplification', 'way_of_working', 'Make complex business problems understandable and actionable.'),
  ('Stakeholder alignment', 'stakeholder-alignment', 'way_of_working', 'Build shared understanding across stakeholders.'),
  ('Knowledge sharing', 'knowledge-sharing', 'way_of_working', 'Share knowledge in a clear and useful way.'),
  ('Reliable follow-through', 'reliable-follow-through', 'way_of_working', 'Make commitments visible and follow through consistently.'),
  ('Human-centered automation', 'human-centered-automation', 'way_of_working', 'Design automation that respects human judgment and exception handling.')
on conflict (slug) do nothing;